/*
 * File: app/controller/phone/Main.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Envicool.controller.phone.Main', {
    extend: 'Ext.app.Controller',

    config: {
        models: [
            'ProdInfo'
        ],
        stores: [
            'ProdInfoStore'
        ],

        refs: {
            inforPage: 'carousel#mycarousel1',
            phoneMain: 'tabpanel#mytabpanel'
        },

        control: {
            "carousel#mycarousel1": {
                initialize: 'onCarouselInitialize'
            }
        }
    },

    onCarouselInitialize: function(component, eOpts) {

                var categories = ['Food', 'Animals', 'Cars', 'Architecture'],
                    itemsCountPerCategory = 10,
                    horizontalCarousels = [],
                    items, i, j, ln, category;

                //now we loop through each of the categories
                for (i = 0,ln = categories.length; i < ln; i++) {
                    items = [];
                    category = categories[i];
                    for(j=1;j <= itemsCountPerCategory;j++){
                        items.push({
                            xtype:'container',
                            layout:{
                                type:'vbox',
                                pack:'justify'
                            },
                            items:[{
                                flex:1,
                                xtype: 'image',
                                cls: 'my-carousel-item-img',
                                src: 'resources/images/photos/'+ category + '/'  + j + '.jpg'
                            },
                            {
                                flex:1,
                                xtype: 'container',
                                styleHtmlContent:true,
                                html:'搞一堆文字'
                            }
                            ]
                        });
                    }
                    horizontalCarousels.push({
                        xtype: 'carousel',

                        //the direction is horizontal
                        direction: 'horizontal',

                        //we turn on direction lock so you cannot scroll diagonally
                        directionLock: true,

                        //and give it the items array
                        items: items
                    });
                }
                component.add(horizontalCarousels);
    },

    launch: function() {

    }

});