/*
 * File: app/controller/phone/Main.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Envicool.controller.phone.Main', {
    extend: 'Ext.app.Controller',

    config: {
        models: [
            'ProdInfo'
        ],
        stores: [
            'ProdInfoStore'
        ],

        refs: {
            inforPage: 'carousel#mycarousel1',
            phoneMain: 'tabpanel#mytabpanel'
        },

        control: {
            "carousel#mycarousel1": {
                initialize: 'onCarouselInitialize'
            }
        }
    },

    onCarouselInitialize: function(component, eOpts) {
                var items = [],
                    newActiveItem = component;
                for(var i=1;i<=10;i++){
                    items.push({
                        xtype:'container',
                        layout:{
                            type:'vbox',
                            pack:'justify'
                        },
                        items:[{
                            flex:1,
                            xtype: 'image',
                            cls: 'my-carousel-item-img',
                            src: 'resources/images/photos/Cars/' + i + '.jpg'
                        },
                        {
                            flex:1,
                            xtype: 'container',
                            styleHtmlContent:true,
                            html:'搞一堆文字'
                        }
                        ]
                    });
                }
                newActiveItem.add(items);
    },

    launch: function() {

    }

});