/*
 * File: app/view/phone/Main.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Envicool.view.phone.Main', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.MainView',

    requires: [
        'Envicool.view.MyPanel1',
        'Ext.carousel.Carousel',
        'Ext.tab.Bar',
        'Ext.Panel'
    ],

    config: {
        items: [
            {
                xtype: 'carousel',
                iconCls: 'info',
                itemId: 'mycarousel1',
                direction: 'vertical'
            },
            {
                xtype: 'panel',
                iconCls: 'favorites',
                html: '我勒个去'
            },
            {
                xtype: 'mypanel1',
                html: 'HomePage',
                iconCls: 'home'
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});