/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({

    requires: [
        'Ext.MessageBox'
    ],
    views: [
        'MyPanel1'
    ],
    controllers: [
        'phone.Main'
    ],
    isIconPrecomposed: true,
    name: 'Envicool',

    onUpdated: function() {
                Ext.Msg.confirm(
                    "Application Update",
                    "This application has just successfully been updated to the latest version. Reload now?",
                    function(buttonId) {
                        if (buttonId === 'yes') {
                            window.location.reload();
                        }
                    }
                );
    },

    launch: function() {

        Ext.create('Envicool.view.phone.Main', {fullscreen: true});
    }

});
